source 'https://github.com/CocoaPods/Specs.git'

target 'ReactiveCocoaStoryBoardDemo_Example', :exclusive => true do
  pod "ReactiveCocoaStoryBoardDemo", :path => "../"
end

target 'ReactiveCocoaStoryBoardDemo_Tests', :exclusive => true do
  pod "ReactiveCocoaStoryBoardDemo", :path => "../"

end

pod 'HFTableCollectionBindingHelper'
