source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ReactiveCocoaStoryBoardDemo_Example', :exclusive => true do
  pod "ReactiveCocoaStoryBoardDemo", :path => "../"
end

target 'ReactiveCocoaStoryBoardDemo_Tests', :exclusive => true do
  pod "ReactiveCocoaStoryBoardDemo", :path => "../"

  
end
